export const quotes = [
  "Seja luz na vida das pessoas.",
  "Solidariedade é o amor em movimento.",
  "Cuide bem. Olhe nos olhos. Tente reparar no que ninguém repara. Ouça. Seja sincero. O amor se constrói na simplicidade.",
  "Um elogio sincero pode mudar o seu dia, que tal mudar o dia de alguém hoje?",
  "A vida é uma estrada, então me deixa te levar pra caminhar.",
  "Nunca é tarde pra pegar uma velha história e escrever um novo final.",
  "Dê valor a quem te dá amor.",
  "Entre o ir e o ficar, que fique o melhor e que se vá o que nada me acrescentará.",
  "Pequenas coisas tornam-se grandes quando feitas com amor.",
  "Somos mais fortes do que parecemos e mais duros do que pensamos.",
  "Não se cubra de razão, se cubra de amor e descubra a razão de tudo!",
  "Coloca o mundo no mudo e escuta o seu coração.",
  "Cada pessoa que amamos é um achado. Cada momento juntos é um tesouro. Cada dia de vida que temos é um presente.",
  "Eu acredito que o sentido da vida seja fazer sentido a outras vidas.",
  'Coloque "ser feliz" no topo da sua lista de prioridades.',
  "Mulher... Mesmo brava é linda. Mesmo alegre, chora. Mesmo tímida, comemora. Mesmo apaixonada, ignora. Mesmo frágil é poderosa.",
  "Cumplicidade é saber que se tem alguém para dividir o que não podemos carregar sozinhos.",
  "Encher o coração de coisas boas é a melhor forma de se proteger contra o mal.",
  "O que não te mata, te fortalece.",
  "Compreender é também uma forma de amor!",
  "O sorriso é a beleza interior abrindo a janela para refrescar a alma.",
  "Se você deseja o bem, o bem deseja você!",
  "O amor é a flor mais bonita que o coração da gente produz. ",
  "Faça todo o bem que puder, usando todos os meios que puder, de todas as maneiras que puder… para todas as pessoas que puder, durante o maior tempo que puder.",
  "Sempre acredite que algo maravilhoso está prestes a acontecer.",
  "Na vida, deixe pegadas. Nunca cicatrizes.",
  "Uma pessoa que é legal com você mas não é legal com um garçom não é uma pessoa legal.",
  "Na vida, quem perde o telhado, em troca recebe as estrelas.",
  "A velhice chega para todos. Não abandone quem passou a vida inteira com você.",
  "Coma menos açúcar. Você já é suficientemente doce.",
  "Hoje é um dia perfeito para ser feliz.",
  "Fazer o outro feliz é ser feliz sem saber.",
  "O amor e a solidariedade recarregam a pilha de qualquer um. Não cobre, ofereça!",
  "Grandes mudanças acontecem de dentro pra fora.",
  "Nunca deixe as coisas que você quer fazê-lo esquecer das coisas que você tem.",
  "Gente legal atrai gente legal.",
  "Seja quem você quer ter por perto.",
  "O único item de valor na vida é o tempo que você passa com quem ama.",
  "Segura teu filho no colo, sorria e abraça os teus pais enquanto estão aqui.",
  "Salve-se quem quiser, perca-se quem puder.",
  "Preserve. Pessoas boas estão sendo extintas.",
  "Nenhum lugar é melhor do que perto.",
  "Não há beleza que substitua o charme de carregar com classe as suas imperfeições. ",
  "Que a pressa das horas e o cinza do dia não te faça perder o sorriso nem as cores que a felicidade te presenteou!",
  "Chegando ao destino não se esqueça de onde partiu.",
  "Nada do que vivemos tem sentido se não tocarmos o coração das pessoas.",
  "Quando a felicidade de alguém é a sua felicidade isso é amor.",
  "São as coisas bobas que me encantam e as sinceras que me apaixonam.",
  "O mundo fica mais bonito quando a gente carrega coisas boas no peito.",
  "Sorrir não gasta eletricidade e gera muito mais luz!",
  "Cerque-se de pessoas leves, com palavras simples que te tiram o chão. ",
  "A felicidade deveria ser assim mesmo, sem data, sem encomenda, medo de existir. Os dias mais felizes são aqueles com menos planos na agenda.",
  "Pra lá enquanto houver trem, pra cima enquanto houver além e pra sempre enquanto houver quem. ",
  "Eu não sou de demonstrar sentimentos, mas sou cheio deles... Eu sofro em silêncio, amo com o olhar e falo por sorrisos. ",
  "Me encanto com os caminhos que separam as chegadas das partidas, com os intervalos da vida e as infinitas possibilidades que moram ali.",
  "Bonito é ser feliz e acreditar que a sorte é você quem traz! ",
  "E que hoje nada te atrapalhe, nada te incomode, nada te provoque pro lado ruim. É tempo de deixar a vida acontecer, amar quem é preciso amar e sorrir com o que te faz bem.",
  "Seja como for o amor, é transformador.",
  "Eu acredito na beleza em suas várias formas.",
  "Que o amor seja regra e jamais exceção! ",
  "Que a gente consiga caminhos tranquilos, espaços sossegados e momentos de alegria dentro de nós. Que a leveza fique em cada canto e a harmonia em cada passo. ",
  "Menos carão, mais carinho.",
  "Às vezes nem me preocupo tanto comigo... Mas há pessoas que amo e não quero vê-las sofrer.",
  "O amor é uma pena que deve ser cumprida em regime de felicidade plena.",
  "Apesar de toda a confusão, está tudo em ordem!",
  "Somos pequenas explosões de emoções o tempo todo. Seja um instante de amor! ",
  "A bondade não consiste na grandeza, mas a grandeza consiste na bondade.   ",
  "Quando se aprende a amar, o mundo passa a ser seu.",
  "Você sabe que alguém te ama não pelo que ele fala, mas pelo o que faz. O amor não sobrevive de teorias.",
  "Eu só acredito em liberdade e estar sempre com saudade de viver um grande amor.",
  "Eu canto porque o instante existe e a minha vida está completa. Não sou alegre nem sou triste: sou poeta.",
  "Se você souber olhar as coisas de um jeito mágico, tudo fica mais bonito.",
  "Para viajar basta existir.",
  "Um poeta é sempre irmão do vento e da água: deixa seu ritmo por onde passa. ",
];
